<?php
/**
 * Copyright © Nimasystems (info@nimasystems.com). All rights reserved.
 * Please visit Nimasystems.com for license details
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Nimasystems\Freshchat\Block\Chat;

/** @var $block Chat */

$isFreshdeskEnabled = $block->isFreshdeskEnabled();
$freshdeskWidgetJsSrc = $block->getFreshdeskWidgetJsSrc();

/** @var Template $block */
/** @var Escaper $escaper */
$escaper = $escaper ?? $block;

?>
<?php if ($isFreshdeskEnabled && $freshdeskWidgetJsSrc): ?>
<script src='//eu.fw-cdn.com/<?= $freshdeskWidgetJsSrc ?>"></script>
<?php endif; ?>
